# Generated by Django 5.2.10 on 2026-01-09 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, help_text='Unique transaction reference', max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posted', models.BooleanField(default=False, help_text='Whether this entry is finalized')),
                ('description', models.CharField(max_length=500)),
                ('entry_type', models.CharField(help_text='Type of entry (FAUCET, INVESTMENT, TRANSFER, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'db_table': 'journal_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('category', models.CharField(choices=[('USER_WALLET', 'User Wallet'), ('SYSTEM_RESERVE', 'System Reserve'), ('ASSET_ESCROW', 'Asset Escrow'), ('FEE_COLLECTION', 'Fee Collection')], max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_accounts',
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Positive=Debit, Negative=Credit', max_digits=20)),
                ('balance_snapshot', models.DecimalField(decimal_places=8, help_text='Account balance after this transaction', max_digits=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_lines',
                'ordering': ['journal_entry', 'id'],
            },
        ),
    ]
