# Generated by Django 5.2.10 on 2026-01-09 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null for system accounts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='ledger.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='transactionline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['tenant', 'category'], name='ledger_acco_tenant__cc133d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['owner', 'category'], name='ledger_acco_owner_i_70005d_idx'),
        ),
    ]
