# Generated by Django 5.2.10 on 2026-01-09 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('TECH_STOCKS', 'Tech Stocks'), ('COMMODITIES', 'Commodities'), ('BONDS', 'Bonds'), ('CRYPTO', 'Cryptocurrency'), ('PRIVATE_EQUITY', 'Private Equity'), ('ART', 'Art & Collectibles')], max_length=30)),
                ('valuation', models.DecimalField(decimal_places=8, help_text='Current price per share', max_digits=20)),
                ('total_shares', models.DecimalField(decimal_places=8, help_text='Total shares available for this asset', max_digits=20)),
                ('risk_level', models.IntegerField(default=3, help_text='Risk level (1=Low, 5=High)')),
                ('accreditation_required', models.BooleanField(default=False, help_text='Requires accredited investor status')),
                ('minimum_investment', models.DecimalField(decimal_places=8, default=Decimal('10.00'), max_digits=20)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_shares', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Shares available for purchase', max_digits=20)),
                ('sold_shares', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Shares that have been sold', max_digits=20)),
                ('reserved_shares', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Shares reserved for pending transactions', max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Asset inventories',
                'db_table': 'asset_inventory',
            },
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
