# Generated by Django 5.2.10 on 2026-01-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='assetpricehistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.asset'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'asset_type'], name='assets_tenant__927741_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['risk_level'], name='assets_risk_le_86ffa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('tenant', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='assetpricehistory',
            index=models.Index(fields=['asset', 'recorded_at'], name='asset_price_asset_i_f05f68_idx'),
        ),
    ]
